# Generated by Django 5.0.4 on 2024-04-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_exercise_workout_alter_entry_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')])),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='body_part',
        ),
        migrations.AddField(
            model_name='workout',
            name='day',
            field=models.ManyToManyField(to='journal.day'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.ManyToManyField(to='journal.bodypart'),
        ),
    ]
