# Generated by Django 5.0.4 on 2024-04-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_day_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (4, 'Wednesday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reps',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sets',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
