# Generated by Django 5.0.4 on 2024-04-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_day_day_alter_entry_reps_alter_entry_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sub_body_part',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
