# Generated by Django 5.0.4 on 2024-04-25 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_day_day_alter_exercise_sub_body_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='trainee',
            field=models.ForeignKey(default='house', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
