# Generated by Django 5.0.4 on 2024-04-30 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_exercise_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
