# Generated by Django 5.0.4 on 2024-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_entry_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Sunday'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')]),
        ),
    ]
