# Generated by Django 5.0.4 on 2024-05-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_alter_day_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.program'),
        ),
    ]
