# Generated by Django 5.0.4 on 2024-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_alter_user_current_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='program',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ManyToManyField(to='journal.workout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='program',
            field=models.ManyToManyField(to='journal.program'),
        ),
    ]
