# Generated by Django 5.0.4 on 2024-05-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_remove_workout_program_workout_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='program',
            field=models.ForeignKey(default='a5cfd68d-9fab-4489-87c8-96a18210bd05', on_delete=django.db.models.deletion.CASCADE, to='journal.program'),
            preserve_default=False,
        ),
    ]
