# Generated by Django 5.0.4 on 2024-06-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_alter_workout_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
