# Generated by Django 5.0.4 on 2024-12-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_alter_exercise_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='sub_body_part',
        ),
    ]
